"""Tweet and user cache tables

Revision ID: 002
Revises: 001
Create Date: 2024-11-08 20:54:30.107343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tweet_id', sa.String(), nullable=False),
    sa.Column('tweet_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tweet_cache')),
    sa.UniqueConstraint('tweet_id', name='uq_tweet_id'),
    sa.UniqueConstraint('tweet_id', name=op.f('uq__tweet_cache__tweet_id'))
    )
    op.create_table('user_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('follower_count', sa.BigInteger(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_cache')),
    sa.UniqueConstraint('user_id', name='uq_user_id'),
    sa.UniqueConstraint('user_id', name=op.f('uq__user_cache__user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cache')
    op.drop_table('tweet_cache')
    # ### end Alembic commands ###
