"""Receipts removed discovery updated

Revision ID: 004
Revises: 003
Create Date: 2024-12-23 18:53:44.483704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_miner_receipts_miner_key_timestamp', table_name='miner_receipts')
    op.drop_index('idx_miner_receipts_timestamp', table_name='miner_receipts')
    op.drop_index('idx_miner_receipts_token_timestamp', table_name='miner_receipts')
    op.drop_index('idx_miner_receipts_validator_key_timestamp', table_name='miner_receipts')
    op.drop_table('miner_receipts')
    op.add_column('miner_discoveries', sa.Column('ipfs_link', sa.String(), nullable=False))
    op.drop_column('miner_discoveries', 'total_challenges')
    op.drop_column('miner_discoveries', 'graph_db')
    op.drop_column('miner_discoveries', 'failed_challenges')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_discoveries', sa.Column('failed_challenges', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('miner_discoveries', sa.Column('graph_db', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('miner_discoveries', sa.Column('total_challenges', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('miner_discoveries', 'ipfs_link')
    op.create_table('miner_receipts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('miner_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('query_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('validator_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('result_hash_signature', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk__miner_receipts'),
    sa.UniqueConstraint('miner_key', 'request_id', name='uq_miner_key_request_id')
    )
    op.create_index('idx_miner_receipts_validator_key_timestamp', 'miner_receipts', ['validator_key', 'timestamp'], unique=False)
    op.create_index('idx_miner_receipts_token_timestamp', 'miner_receipts', ['token', 'timestamp'], unique=False)
    op.create_index('idx_miner_receipts_timestamp', 'miner_receipts', ['timestamp'], unique=False)
    op.create_index('idx_miner_receipts_miner_key_timestamp', 'miner_receipts', ['miner_key', 'timestamp'], unique=False)
    # ### end Alembic commands ###
